name: Daily Market Update

on:
  schedule:
    - cron: '30 9 * * *' # UTC 기준 09:30은 한국시간 18:30입니다.
  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install libraries
        run: |
          pip install pandas sqlalchemy pymysql cryptography pykrx yfinance
      - name: Run Update Script
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python update_db.py
