name: Daily Market Update

on:
  schedule:
    # 한국 시간(KST) 오후 4시는 UTC 기준으로 오전 7시입니다. (월~금요일에만 실행)
    - cron: '0 7 * * 1-5' 
  workflow_dispatch: # 수동 실행 버튼

jobs:
  update-database:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          pip install pandas sqlalchemy pymysql cryptography pykrx yfinance

      - name: Run Update Script to MySQL
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python update_db.py
